# Pre-commit hooks configuration
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      # Run the linter and auto-fix issues (includes import sorting)
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for files that contain merge conflict markers
      - id: check-merge-conflict
      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict
      # Check for files with names that would conflict on case-insensitive filesystems
      - id: check-added-large-files
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Check YAML files for parseable syntax
      - id: check-yaml
      # Check TOML files for parseable syntax
      - id: check-toml